<template>
  <div class="mt-4" id="download-files">
    <UCard>
      <div class="flex flex-col items-center gap-4">
        <div class="flex items-center gap-3">
          <UButton
            @click="downloadConfig"
            icon="i-heroicons-arrow-down-tray"
            size="lg"
            color="primary"
          >
            Download Config (.wsb)
          </UButton>

          <UButton
            @click="copyToClipboard"
            icon="i-heroicons-clipboard-document"
            variant="outline"
            size="lg"
          >
            Copy to Clipboard
          </UButton>
        </div>
      </div>
    </UCard>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  config: any;
}>();

const generatedConfig = () => {
  let xml =
    "<!-- Generated by Windows Sandbox Web Config Tool - https://github.com/AdrianoCahete/WinSandbox_UI-config -->\n";
  xml += "<Configuration>\n";

  for (const [key, value] of Object.entries(props.config)) {
    if (key === "MappedFolders" || key === "LogonCommand") {
      continue;
    }

    if (value !== null && value !== undefined) {
      const outputValue =
        typeof value === "boolean" ? (value ? "Enable" : "Disable") : value;
      xml += `  <${key}>${outputValue}</${key}>\n`;
    }
  }

  const mappedFolders = props.config.MappedFolders.filter(
    (folder: any) => folder.HostFolder && folder.HostFolder.trim() !== ""
  );

  if (mappedFolders.length > 0) {
    xml += "  <MappedFolders>\n";
    for (const folder of mappedFolders) {
      xml += "    <MappedFolder>\n";
      xml += `      <HostFolder>${folder.HostFolder}</HostFolder>\n`;
      if (folder.SandboxFolder && folder.SandboxFolder.trim() !== "") {
        xml += `      <SandboxFolder>${folder.SandboxFolder}</SandboxFolder>\n`;
      }
      xml += `      <ReadOnly>${
        folder.ReadOnly === true ? "true" : "false"
      }</ReadOnly>\n`;
      xml += "    </MappedFolder>\n";
    }
    xml += "  </MappedFolders>\n";
  }

  if (props.config.LogonCommand && props.config.LogonCommand.trim() !== "") {
    xml += "  <LogonCommand>\n";
    xml += `    <Command>${props.config.LogonCommand}</Command>\n`;
    xml += "  </LogonCommand>\n";
  }

  xml += "</Configuration>";
  return xml;
};

const copyToClipboard = async () => {
  try {
    await navigator.clipboard.writeText(generatedConfig());
    console.log("Configuration copied to clipboard!");
  } catch (err) {
    console.error("Failed to copy:", err);
  }
};

const downloadConfig = () => {
  const blob = new Blob([generatedConfig()], { type: "application/xml" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  const filename = `WinSandbox_${year}-${month}-${day}.wsb`;

  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
</script>
